services:
    php-apache:
        build: .
        container_name: php_chatboard
        ports: [8080:80]
        depends_on: [mysql]
        networks: [network]
    mysql:
        image: mysql
        container_name: php_chatboard_mysql
        networks: [network]
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
        volumes: 
            - mysql_volume:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    mysql_volume:
networks:
    network:
